architecture: cifar100_vgg11_bn

# Canonical layer packs for ALL datasets that use ResNet-18
layer_packs:
  full:        [features.2, features.6, features.10, features.13, features.17, features.20, features.24, features.27, classifier.5]
  penultimate: [classifier.5]
  partial:     [features.20, features.24, features.27, classifier.5]
  none:        []