architecture: mobilenet_v3_large
source: torchvision
weights: MobileNet_V3_Large_Weights.IMAGENET1K_V1

# Canonical layer packs for ALL datasets that use Mobilenet-v3-large
layer_packs:
  full:
    [
      features.1,
      features.2,
      features.3,
      features.4,
      features.5,
      features.6,
      features.7,
      features.8,
      features.9,
      features.10,
      features.11,
      features.12,
      features.13,
      features.14,
      features.15,
      features,
    ]
  penultimate: [features]
  partial:
    [
      features.10,
      features.11,
      features.12,
      features.13,
      features.14,
      features.15,
      features,
    ]
  none: []
