architecture: regnet_y_16gf
source: torchvision
weights: RegNet_Y_16GF_Weights.IMAGENET1K_V1

# Canonical layer packs for ALL datasets that use Mobilenet-v3-large
layer_packs:
  full:
    [
      trunk_output.block1,
      trunk_output.block2,
      trunk_output.block3,
      trunk_output,
    ]
  penultimate: [trunk_output]
  partial: [trunk_output.block3, trunk_output]
  none: []
