architecture: resnet50

# Canonical layer packs for ALL datasets that use ResNet-50
layer_packs:
  full:        [layer1, layer2, layer3, layer4, avgpool]
  penultimate: [avgpool]
  partial:     [layer3, layer4, avgpool]
  none:        []
