# datasets:  [cifar10, cifar100, imagenet200, imagenet]
# datasets: [cifar10, cifar100]
datasets: [cifar10, cifar100]
methods:
  [
    dknn,
    energy,
    entropy,
    gen,
    gram,
    mahalanobis,
    mls,
    msp,
    odin,
    rmds,
    she,
    vim,
  ]
# methods: [odin]
batch_size: 128
num_workers: 8
