datasets:  [cifar10, cifar100, imagenet200, imagenet]
methods:
  [
    dknn,
    energy,
    entropy,
    gen,
    gram,
    mahalanobis,
    mls,
    msp,
    odin,
    rmds,
    she,
    vim,
  ]

batch_size: 64
num_workers: 8
