class: GEN

base:
  gamma: [0.1]
  k: [5, 50, 100]

modes:
  - {} # "vanilla" GEN
  - { use_react: [True], react_quantile: [0.85, 0.90, 0.95, 0.99] }
  - { use_scale: [True], scale_percentile: [0.85, 0.90, 0.95, 0.99] }
  - { use_ash: [True], ash_percentile: [0.85, 0.90, 0.95, 0.99] }

fit_grid:
  layer_packs: [none]
