class: ODIN

base:
  temperature: [1, 10, 100, 1000]
  noise: [0.0014, 0.0028]

modes:
  - {} # "vanilla" ODIN
  - { use_react: [True], react_quantile: [0.85, 0.90, 0.95, 0.99] }
  - { use_scale: [True], scale_percentile: [0.85, 0.90, 0.95, 0.99] }
  - { use_ash: [True], ash_percentile: [0.85, 0.90, 0.95, 0.99] }

fit_grid:
  layer_packs: [none]
