# Near / far OOD lists – only for this ID dataset
ood:
  near: [cifar10, tin]
  far:  [mnist, svhn, texture, places365]

# Which models (and which layer packs) to try on **this** dataset
models:
  - resnet18
  - cifar100_resnet20
  - cifar100_resnet32
  - cifar100_vgg11_bn
  - cifar100_vgg16_bn
  - cifar100_mobilenetv2_x1_0
  - cifar100_mobilenetv2_x1_4
  - cifar100_shufflenetv2_x1_0
  - cifar100_shufflenetv2_x2_0
  - cifar100_repvgg_a0
  - cifar100_repvgg_a2