# Near / far OOD lists – only for this ID dataset
ood:
  near: [ssb_hard, ninco]
  far: [inaturalist, texture, openimageo]

# Which models (and which layer packs) to try on **this** dataset
models:
  - resnet50
  - vit_b_16
  - vit_b_16_swag_linear
  - mobilenet_v2
  - mobilenet_v3_large
  - regnet_y_16gf

fit_subset: # applies only to the *training* DataLoader
  max_samples: 200_000 # hard cap (after class-balancing)
  per_class: 200 # keep ≤ 200 images per class, balanced
  seed: 0 # reproducible
